# Generated by Django 4.2.4 on 2023-09-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receptpost',
            old_name='category',
            new_name='name',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
